// <auto-generated />
using System;
using Kantonal.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kantonal.Infrastructure.Migrations
{
    [DbContext(typeof(KantonalDbContext))]
    [Migration("20260626125413_AddFinanceIndicators")]
    partial class AddFinanceIndicators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kantonal.Domain.MunicipalFinanceRecord", b =>
                {
                    b.Property<int>("BfsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("bfs_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<decimal?>("BalanceSheetSurplusQuotient")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_sheet_surplus_quotient");

                    b.Property<decimal?>("CapitalServiceShare")
                        .HasColumnType("numeric")
                        .HasColumnName("capital_service_share");

                    b.Property<decimal?>("GrossDebtShare")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_debt_share");

                    b.Property<decimal?>("InterestBurdenShare")
                        .HasColumnType("numeric")
                        .HasColumnName("interest_burden_share");

                    b.Property<decimal?>("InvestmentShare")
                        .HasColumnType("numeric")
                        .HasColumnName("investment_share");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<decimal?>("NetDebtPerCapitaChf")
                        .HasColumnType("numeric")
                        .HasColumnName("net_debt_per_capita_chf");

                    b.Property<decimal?>("NetDebtQuotient")
                        .HasColumnType("numeric")
                        .HasColumnName("net_debt_quotient");

                    b.Property<decimal?>("SelfFinancingRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("self_financing_ratio");

                    b.Property<decimal?>("SelfFinancingShare")
                        .HasColumnType("numeric")
                        .HasColumnName("self_financing_share");

                    b.HasKey("BfsNumber", "Year");

                    b.ToTable("finance_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
