// <auto-generated />
using System;
using Kantonal.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kantonal.Infrastructure.Migrations
{
    [DbContext(typeof(KantonalDbContext))]
    partial class KantonalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kantonal.Domain.MunicipalFinanceRecord", b =>
                {
                    b.Property<int>("BfsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("bfs_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("municipality_name");

                    b.Property<decimal?>("NetDebtPerCapitaChf")
                        .HasColumnType("numeric")
                        .HasColumnName("net_debt_per_capita_chf");

                    b.Property<decimal?>("SelfFinancingRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("self_financing_ratio");

                    b.HasKey("BfsNumber", "Year");

                    b.ToTable("finance_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
